server:
  port: 8011
cas:
  #后端服务地址(回调地址)
  client-host-url: http://192.168.0.113:8011/
  #cas认证中心地址
  server-url-prefix: http://192.168.0.113:8089/cas
  #cas认证中心登录地址
  server-login-url: http://192.168.0.113:8089/cas/login
  #cas不拦截
  ignore-pattern: (/file/*)|(/js)
  enable: true


